base:
  project_name: AI Recriter
  target: Category
  random_state: 42
  resume_category: ['HR', 'DESIGNER', 'INFORMATION_TECHNOLOGY', 'TEACHER', 'ADVOCATE',
       'BUSINESS_DEVELOPMENT', 'HEALTHCARE', 'FITNESS', 'AGRICULTURE',
       'BPO', 'SALES', 'CONSULTANT', 'DIGITAL_MEDIA', 'AUTOMOBILE',
       'CHEF', 'FINANCE', 'APPAREL', 'ENGINEERING', 'ACCOUNTANT',
       'CONSTRUCTION', 'PUBLIC_RELATIONS', 'BANKING', 'ARTS', 'AVIATION']


plot:
  eda_count_plot: plots/eda_count_plot_of_resume_categories.png
  eda_freq_dist_HR: plots/eda_frequency_distribution_HR.png
  eda_freq_dist_DESIGNER: plots/eda_frequency_distribution_DESIGNER.png
  eda_freq_dist_INFORMATION_TECHNOLOGY: plots/eda_frequency_distribution_INFORMATION_TECHNOLOGY.png
  eda_freq_dist_TEACHER: plots/eda_frequency_distribution_TEACHER.png
  eda_freq_dist_ADVOCATE: plots/eda_frequency_distribution_ADVOCATE.png
  eda_freq_dist_BUSINESS_DEVELOPMENT: plots/eda_frequency_distribution_BUSINESS_DEVELOPMENT.png
  eda_freq_dist_HEALTHCARE: plots/eda_frequency_distribution_HEALTHCARE.png
  eda_freq_dist_FITNESS: plots/eda_frequency_distribution_FITNESS.png
  eda_freq_dist_AGRICULTURE: plots/eda_frequency_distribution_AGRICULTURE.png
  eda_freq_dist_BPO: plots/eda_frequency_distribution_BPO.png
  eda_freq_dist_SALES: plots/eda_frequency_distribution_SALES.png
  eda_freq_dist_CONSULTANT: plots/eda_frequency_distribution_CONSULTANT.png
  eda_freq_dist_DIGITAL_MEDIA: plots/eda_frequency_distribution_DIGITAL_MEDIA.png
  eda_freq_dist_AUTOMOBILE: plots/eda_frequency_distribution_AUTOMOBILE.png
  eda_freq_dist_CHEF: plots/eda_frequency_distribution_CHEF.png
  eda_freq_dist_FINANCE: plots/eda_frequency_distribution_FINANCE.png
  eda_freq_dist_APPAREL: plots/eda_frequency_distribution_APPAREL.png
  eda_freq_dist_ENGINEERING: plots/eda_frequency_distribution_ENGINEERING.png
  eda_freq_dist_ACCOUNTANT: plots/eda_frequency_distribution_ACCOUNTANT.png
  eda_freq_dist_CONSTRUCTION: plots/eda_frequency_distribution_CONSTRUCTION.png
  eda_freq_dist_PUBLIC_RELATIONS: plots/eda_frequency_distribution_PUBLIC_RELATIONS.png
  eda_freq_dist_BANKING: plots/eda_frequency_distribution_BANKING.png
  eda_freq_dist_ARTS: plots/eda_frequency_distribution_ARTS.png
  eda_freq_dist_AVIATION: plots/eda_frequency_distribution_AVIATION.png
  #wordcloud
  eda_wordcloud_HR: plots/eda_wordcloud_HR.png
  eda_wordcloud_DESIGNER: plots/eda_wordcloud_DESIGNER.png
  eda_wordcloud_INFORMATION_TECHNOLOGY: plots/eda_wordcloud_INFORMATION_TECHNOLOGY.png
  eda_wordcloud_TEACHER: plots/eda_wordcloud_TEACHER.png
  eda_wordcloud_ADVOCATE: plots/eda_wordcloud_ADVOCATE.png
  eda_wordcloud_BUSINESS_DEVELOPMENT: plots/eda_wordcloud_BUSINESS_DEVELOPMENT.png
  eda_wordcloud_HEALTHCARE: plots/eda_wordcloud_HEALTHCARE.png
  eda_wordcloud_FITNESS: plots/eda_wordcloud_FITNESS.png
  eda_wordcloud_AGRICULTURE: plots/eda_wordcloud_AGRICULTURE.png
  eda_wordcloud_BPO: plots/eda_wordcloud_BPO.png
  eda_wordcloud_SALES: plots/eda_wordcloud_SALES.png
  eda_wordcloud_CONSULTANT: plots/eda_wordcloud_CONSULTANT.png
  eda_wordcloud_DIGITAL_MEDIA: plots/eda_wordcloud_DIGITAL_MEDIA.png
  eda_wordcloud_AUTOMOBILE: plots/eda_wordcloud_AUTOMOBILE.png
  eda_wordcloud_CHEF: plots/eda_wordcloud_CHEF.png
  eda_wordcloud_FINANCE: plots/eda_wordcloud_FINANCE.png
  eda_wordcloud_APPAREL: plots/eda_wordcloud_APPAREL.png
  eda_wordcloud_ENGINEERING: plots/eda_wordcloud_ENGINEERING.png
  eda_wordcloud_ACCOUNTANT: plots/eda_wordcloud_ACCOUNTANT.png
  eda_wordcloud_CONSTRUCTION: plots/eda_wordcloud_CONSTRUCTION.png
  eda_wordcloud_PUBLIC_RELATIONS: plots/eda_wordcloud_PUBLIC_RELATIONS.png
  eda_wordcloud_BANKING: plots/eda_wordcloud_BANKING.png
  eda_wordcloud_ARTS: plots/eda_wordcloud_ARTS.png
  eda_wordcloud_AVIATION: plots/eda_wordcloud_AVIATION.png


data_source:
  data: data/Resume.csv



eda:
  processed_data: data/processed/processed_resume.csv
  data_HR: data/processed/HR.csv
  data_DESIGNER: data/processed/DESIGNER.csv
  data_INFORMATION_TECHNOLOGY: data/processed/INFORMATION_TECHNOLOGY.csv
  data_TEACHER: data/processed/TEACHER.csv
  data_ADVOCATE: data/processed/ADVOCATE.csv
  data_BUSINESS_DEVELOPMENT: data/processed/BUSINESS_DEVELOPMENT.csv
  data_HEALTHCARE: data/processed/HEALTHCARE.csv
  data_FITNESS: data/processed/FITNESS.csv
  data_AGRICULTURE: data/processed/AGRICULTURE.csv
  data_BPO: data/processed/BPO.csv
  data_SALES: data/processed/SALES.csv 
  data_CONSULTANT: data/processed/CONSULTANT.csv 
  data_DIGITAL_MEDIA: data/processed/DEGITAL_MEDIA.csv 
  data_AUTOMOBILE: data/processed/AUTOMOBILE.csv 
  data_CHEF: data/processed/CHEF.csv 
  data_FINANCE: data/processed/FINANCE.csv
  data_APPAREL: data/processed/APPAREL.csv 
  data_ENGINEERING: data/processed/ENGINEERING.csv 
  data_ACCOUNTANT: data/processed/ACCOUNTANT.csv 
  data_CONSTRUCTION: data/processed/CONSTRUCTION.csv 
  data_PUBLIC_RELATIONS: data/processed/PUBLIC_RELATIONS.csv
  data_BANKING: data/processed/BANKING.csv 
  data_ARTS: data/processed/ARTS.csv 
  data_AVIATION: data/processed/AVIATION.csv 



feature_engineering:
  X_train: data/processed/X_train.joblib
  X_test: data/processed/X_test.joblib
  y_train: data/processed/y_train.joblib
  y_test: data/processed/y_test.joblib
  tfidf: data/processed/tfidf.joblib


