# Generated by Django 3.2 on 2022-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(max_length=1000, upload_to='resume')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
